spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/project_database
        username: postgres
        password: jaqueta
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update